import { sanitizeSource } from './core.js';
const API='https://services.leadconnectorhq.com';
const anonymousName='RTRO Anonymous Feedback';
const anonymousEmail='rtro-anonymous-feedback@reasontoreachout.invalid';
const channels=new Set(['Email','Call opener','Voicemail','Text','LinkedIn','Mailed card','Gift/leave-behind']);
const feedbackAnswers=new Set(['Yes','With Edits','No']);
const contactTargets=new Set(['phone','email','booking','video','mailbox_power']);

export function createGhlAdapter({env,fetchImpl=fetch,sleep=(ms)=>new Promise((resolve)=>setTimeout(resolve,ms))}) {
  if (!env.GHL_API_KEY || !env.GHL_LOCATION_ID) return {record:async()=>{throw new Error('GHL integration is not configured.');}};
  const headers={Authorization:`Bearer ${env.GHL_API_KEY}`,Version:'2021-07-28','Content-Type':'application/json',Accept:'application/json'};
  async function request(path,options={}) { for(let attempt=1;attempt<=3;attempt++){const response=await fetchImpl(`${API}${path}`,{...options,headers:{...headers,...options.headers}});if(response.ok)return response.status===204?{}:response.json();const retry=response.status===429||(response.status>=500&&response.status<=599);if(!retry||attempt===3)throw new Error(`LeadConnector ${response.status}`);const retryAfter=Number(response.headers.get('retry-after'));await sleep(Number.isFinite(retryAfter)&&retryAfter>=0?Math.min(retryAfter*1000,1000):50*(2**(attempt-1)));}}
  const search=async(query)=>(await request(`/contacts/?${new URLSearchParams({locationId:env.GHL_LOCATION_ID,query,limit:'100'})}`)).contacts||[];
  async function find(event){if(event.email)return(await search(event.email)).find((c)=>String(c.email||'').toLowerCase()===event.email.toLowerCase());const byEmail=(await search(anonymousEmail)).find((c)=>String(c.email||'').toLowerCase()===anonymousEmail);if(byEmail)return byEmail;return(await search(anonymousName)).find((c)=>`${c.name||`${c.firstName||''} ${c.lastName||''}`}`.trim().toLowerCase()===anonymousName.toLowerCase());}
  const tagsFor=(event)=>[event.type==='lead_capture'&&'RTRO - PDF Download',event.source&&`RTRO - Source: ${sanitizeSource(event.source)}`,event.consent===true&&'RTRO - Consent Yes',channels.has(event.channel)&&['Mailed card','Gift/leave-behind'].includes(event.channel)&&'RTRO - Physical Mail Interest',event.type==='feedback'&&feedbackAnswers.has(event.answer)&&`RTRO - Feedback: ${event.answer}`,event.type==='wording_copied'&&'RTRO - Copied Wording',event.type==='contact_click'&&contactTargets.has(event.target)&&(event.target==='mailbox_power'?'RTRO - Clicked Mailbox Power':'RTRO - Clicked Contact')].filter(Boolean).filter((v,i,a)=>a.indexOf(v)===i);
  async function readContact(id){const contact=(await request(`/contacts/${id}`)).contact;if(contact?.id!==id)throw new Error('LeadConnector contact readback mismatch.');return contact;}
  const normalized=(value)=>String(value??'').normalize('NFKC').trim().replace(/\s+/g,' ').toLowerCase();
  function verifyCreatedContact(contact,body){for(const key of ['firstName','lastName','name','companyName','locationId','source','email']){if(!Object.hasOwn(body,key))continue;if(!Object.hasOwn(contact,key)||normalized(contact[key])!==normalized(body[key]))throw new Error('LeadConnector contact readback mismatch.');}if(!Object.hasOwn(contact,'tags'))throw new Error('LeadConnector contact readback mismatch.');const expected=new Set((body.tags||[]).map(normalized));const actual=new Set((contact.tags||[]).map(normalized));if(expected.size!==actual.size||[...expected].some((tag)=>!actual.has(tag)))throw new Error('LeadConnector contact readback mismatch.');}
  async function upsert(event){let contact=await find(event);const tags=tagsFor(event);if(!contact){const body=event.email?{locationId:env.GHL_LOCATION_ID,firstName:event.firstName||'RTRO User',email:event.email,companyName:event.company||'',source:sanitizeSource(event.source),tags}:{locationId:env.GHL_LOCATION_ID,name:anonymousName,firstName:'RTRO Anonymous',lastName:'Feedback',email:anonymousEmail,source:'Reason to Reach Out',tags};contact=(await request('/contacts/',{method:'POST',body:JSON.stringify(body)})).contact;if(!contact?.id)throw new Error('LeadConnector contact create returned no target.');contact=await readContact(contact.id);verifyCreatedContact(contact,body);return contact;}if(tags.length){await request(`/contacts/${contact.id}/tags`,{method:'POST',body:JSON.stringify({tags})});contact=await readContact(contact.id);const actual=new Set((contact.tags||[]).map((tag)=>String(tag).toLowerCase()));if(!tags.every((tag)=>actual.has(tag.toLowerCase())))throw new Error('LeadConnector contact tag readback mismatch.');}return contact;}
  const noteFor=(event)=>[`RTRO event: ${event.type}`,`Timestamp: ${event.timestamp}`,`Source: ${sanitizeSource(event.source)}`,...(channels.has(event.channel)?[`Recommended channel: ${event.channel}`]:[]),...(event.type==='lead_capture'?[`Consent: ${event.consent?'Yes':'No'}`,`App user: ${event.firstName}`,`App user email: ${event.email}`,...(event.company?[`App user company: ${event.company}`]:[])]:[]),...(event.type==='feedback'&&feedbackAnswers.has(event.answer)?[`Answer: ${event.answer}`]:[]),...(event.type==='contact_click'&&contactTargets.has(event.target)?[`Target: ${event.target}`]:[])].join('\n');
  return {record:async(event)=>{const contact=await upsert(event);const body=noteFor(event);const created=(await request(`/contacts/${contact.id}/notes`,{method:'POST',body:JSON.stringify({body})})).note;if(!created?.id)throw new Error('LeadConnector note create returned no target.');const readback=(await request(`/contacts/${contact.id}/notes/${created.id}`)).note;if(readback?.id!==created.id||readback.contactId!==contact.id||readback.body!==body)throw new Error('LeadConnector note readback mismatch.');return {ok:true};}};
}
